import * as seed from "./seed-data.js";

const RAW = Symbol("raw");
const raw = (sql) => ({ [RAW]: sql });
const lit = (v) => {
  if (v === null || v === undefined) return "null";
  if (v[RAW]) return v[RAW];
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

function upsert(table, rows, conflict = "id") {
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]);
  const keys = conflict.split(",");
  const values = rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(", ")})`).join(",\n");
  const updates = cols.filter((c) => !keys.includes(c)).map((c) => `${c} = excluded.${c}`).join(", ");
  return `insert into ${table} (${cols.join(", ")}) values\n${values}\non conflict (${conflict}) do ${updates ? `update set ${updates}` : "nothing"};\n\n`;
}

// Verticals may already exist with other ids → always reference them by slug.
const slugOf = Object.fromEntries(seed.VERTICALS.map((v) => [v.id, v.slug]));
const byVertical = (rows) => rows.map((r) => ({ ...r, vertical_id: raw(`(select id from verticals where slug = '${slugOf[r.vertical_id]}')`) }));

export function seedSql() {
  return `-- ============================================================
-- Bridges Live — seed data (verticals, orgs, host, listings, live streams).
-- GENERATED by \`npm run db:build-sql\` from server/seed-data.js. Idempotent.
-- Run after schema.sql and migrations/002_live_commerce.sql.
-- ============================================================
` +
    upsert("verticals", seed.VERTICALS.map(({ id, ...v }) => v), "slug") +
    upsert("organizations", byVertical(seed.ORGS)) +
    upsert("users", seed.USERS.map(({ id, ...u }) => u), "email") +
    upsert("listings", byVertical(seed.LISTINGS)) +
    upsert("shows", byVertical(seed.SHOWS).map((r) => ({ ...r, host_id: raw(`(select id from users where email = '${seed.USERS[0].email}')`) }))) +
    upsert("show_listings", seed.SHOW_LISTINGS, "show_id,listing_id") +
    upsert("streams", seed.STREAMS);
}
